### ISSUE TITLE
The Requirements.txt does not have all the module's [BUG]

### ISSUE THREAD

**Issue by Ahv-gamerboy** [ChaitanyaPy/dal_assessments#167]
**Describe the bug**
Can't run main.py asking for no module, after installing the reqirements.txt this same error

**Device**
Type: Computer
OS: Windows
Browser: Chrome

**Additional context**
Pls update the requirements.txt or list the needed modules

**Comment by ChaitanyaPy** [comment]
Updated requirements.txt in #168
